<template>
  <div>
    <div class="max-w-screen-lg mx-auto py-5 px-2">
      <div class="">
        <div class="">
          <div class="flex flex-wrap items-center mx-auto">
            <div class="md:w-2/3 md:text-left text-center mx-auto">

              <h1 class="sm:text-5xl text-2xl text-warning font-black">HOW TO CHECK FAIRNESS?</h1>
              <p class="py-6 md:w-4/5 text-lg font-normal">Every Lucky result on 777OC is absolutely random. Check it
                yourself!
              </p>
            </div>
            <div class=" w-1/3 p-5">
              <img src="/src/assets/char-2.png" class="animate-geser w-48 " />
            </div>
          </div>

          <div class="mt-5">
            <h3 class="sm:text-2xl text-xl text-secondary font-bold">HOW DOES IT WORK?</h3>
            <p class="py-5 md:w-4/5 text-lg font-normal">The provably fair principle is based on SHA256 technology the
              same as Bitcoin. The procedure of checking bets result allows you to verify the fairness of each bet.
            </p>
          </div>
          <div class="grid sm:grid-cols-3 grid-cols-1 gap-4">
            <div class="mx-auto items-center bg-base-200 duration-300 hover:bg-base-200 p-5 rounded-xl">
              <img class=" w-24 mr-4 group-hover:scale-110 duration-300" src="/src/assets/icon-wd.png"
                alt="illustration" loading="lazy">
              <h2 class="font-bold text-secondary mb-1 text-xl mt-8">Press fairness<br>
                <span class="font-normal text-white">Before placing a bet you may check the hash of the next round
                  number in the "Fairness" pop-up. Hash is a random result, generated and mixed with random Server seed.
                  Every round has its own hash. No-one knows the result before placing a bet.</span>
              </h2>
            </div>
            <div class="mx-auto items-center bg-base-200 duration-300 hover:bg-base-200 p-5 rounded-xl">
              <img class=" w-24 mr-4 group-hover:scale-110 duration-300" src="/src/assets/icon-rafle.png"
                alt="illustration" loading="lazy">
              <h2 class="font-bold text-secondary mb-1 text-xl mt-8">Place a bet<br>
                <span class="font-normal text-white">During the bet, the result is fixed in a special "Random Seed"
                  field. By clicking "Fairness" you can find the current round hash (encrypted winning result) and
                  history of completed bets with all the details.</span>
              </h2>
            </div>
            <div class="mx-auto items-center bg-base-200 duration-300 hover:bg-base-200 p-5 rounded-xl">
              <img class=" w-24 mr-4 group-hover:scale-110 duration-300" src="/src/assets/icon-allgames.png"
                alt="illustration" loading="lazy">
              <h2 class="font-bold text-secondary mb-1 text-xl mt-8">Check hash<br>
                <span class="font-normal text-white">Click "Check". Then in the opened window paste Random Seed you've
                  copied. The issued hash below must match that fixed on 777OC.</span>
              </h2>
            </div>
          </div>

          <div class="my-2 mt-8 flex items-center">
            <h3 class="text-2xl text-primary-content">FAQ<span class="font-black text-primary-content">
                ?</span>
            </h3>
          </div>

          <div class="sm:flex space-x-4">
            <div class="w-1/2 space-y-2">
              <div tabindex="0" class="collapse collapse-plus border border-base-300 bg-base-300 rounded-box">
                <div class="collapse-title text-primary-content text-xl font-medium">
                  What is a Server Seed ?
                </div>
                <div class="collapse-content">
                  <p>Server Seed is a random sequence of 64 symbols (numbers and letters) generated by a server.</p>
                </div>
              </div>
              <div tabindex="0" class="collapse collapse-plus border border-base-300 bg-base-300 rounded-box">
                <div class="collapse-title text-primary-content text-xl font-medium">
                  What is a Random Seed?
                </div>
                <div class="collapse-content">
                  <p>Random seed is a combination of Random winning number and Server seed.</p>
                </div>
              </div>
              <div tabindex="0" class="collapse collapse-plus border border-base-300 bg-base-300 rounded-box">
                <div class="collapse-title text-primary-content text-xl font-medium">
                  What is a Hash Round?
                </div>
                <div class="collapse-content">
                  <p>It’s a specific formula for turning a piece of digital data like a paragraph of text or a file,
                    into a line of characters called a hash of the data.</p>
                </div>
              </div>

            </div>
            <div class="w-1/2 space-y-2">
              <div tabindex="0" class="collapse collapse-plus border border-base-300 bg-base-300 rounded-box">
                <div class="collapse-title text-primary-content text-xl font-medium">
                  Why SHA-256?
                </div>
                <div class="collapse-content">
                  <p>
                    Presently SHA-256 is the most secure hashing function. This function expresses the possible
                    combinations or values that result from the given input data. Using the SHA-256 function makes it
                    (nearly) impossible to duplicate a hash because there are just too many combinations to try and
                    process.
                  </p>
                </div>
              </div>
              <div tabindex="0" class="collapse collapse-plus border border-base-300 bg-base-300 rounded-box">
                <div class="collapse-title text-primary-content text-xl font-medium">
                  How does hashing proceed?
                </div>
                <div class="collapse-content">
                  <p>
                    The provably fair system on 777OC is based on the SHA256 algorithm and consists of Random seed.
                    Every round has its own hash that consists of Random winning uniquely generated for every bet.
                  </p>
                </div>
              </div>
              <div tabindex="0" class="collapse collapse-plus border border-base-300 bg-base-300 rounded-box">
                <div class="collapse-title text-primary-content text-xl font-medium">
                  When is the random number generated?
                </div>
                <div class="collapse-content">
                  <p>
                    Random Lucky result is generated and mixed with random Server seed for every bet. You may see the
                    Hash round before you make a bet in the Fairness section.
                  </p>
                </div>
              </div>

            </div>
          </div>


        </div>
      </div>
    </div>
  </div>
</template>

<script setup>

</script>